### ISSUE TITLE
Cannot run tests selectively

### ISSUE THREAD

**Issue by Fishbowler** [IcedFrisby/IcedFrisby#91]
I've got a need to run _some_ of my tests, (e.g. ones safe to run against Live)
Mocha docs imply I can do this with `--grep [regex]` or `--fgrep [string]`

But it doesn't work with IcedFrisby.

Here's a trivial example: https://github.com/Fishbowler/playground-icedfrisby/blob/master/specs/wikimedia/wiktionary_spec.js

From the root of this repo, the following things happen:

`mocha '**/*_spec.js' --fgrep '@important'`
Prints the first and third describe/it but runs no tests. This is my real use case.

`mocha '**/*_spec.js' --fgrep 'purple'`
0 tests found

`mocha '**/*_spec.js' --fgrep 'important'`
Prints the first and third describe/it, but runs the third one

Seems you need the word in both the it(...) and the frisby.create(...) for it to actually run the test.

I'd rewrite all of the tests to work like the unit tests, using `frisby.create(this.test.title)`, but that triggers a nullref - `test` is undefined.

I've looked through the source and can't see a cause, but also can't see a workaround beyond manually renaming All The Things. Any ideas?

**Comment by paulmelnikow** [comment]
Hey, right, so the root cause is that the Frisby tests do not run inside of the `it()`.

`frisby.create(this.test.title)` like in the unit tests – that's a great idea! It's not working because [arrow functions break `this` in Mocha.](https://mochajs.org/#arrow-functions) Because they bind the invocation calling context to the calling context where the function is defined, Mocha can't override it with its context. It should work if you use `function () {}` instead.

Fun fact: I once wrote an eslint rule `no-mocha-arrows` to check for this! lo1tuma/eslint-plugin-mocha#78

**Comment by Fishbowler** [comment]
Thanks! I've added `no-mocha-arrows` to our eslint config! It caught all the sneaky ones I didn't immediately spot.

I've updated the code sample to include an `.after(..)` - any thoughts on how to access the test title there without stashing it into a variable first? Without it, the after doesn't run.

Is `--fgrep` an antipattern for IcedFrisby? Is there a different way to do this? The only workaround I can think of is to separate tests into files, e.g. myapi_always_spec.js and myapi_dangerous_spec.js and modify the call.

**Comment by cvega** [comment]
I worked around this at Verizon by creating a cli runner that primed test/config data and environment variables. If process.env.deploy=prd, skip destructive tests. I'd love to see a better way using just mocha.

**Comment by paulmelnikow** [comment]
If you're in the icedfrisby object's calling context, it should be in `this.current.describe`. It looks like that should work in an `after()`.

We could handle it in icedfrisby with a `skip` method that takes a bool, similarly to the way we handle `only`. Then you could call `.skip(wantPurple)` and obtain `wantPurple` from the environment.

Though I agree with @cvega that handling it in Mocha would be better.

I like [this solution](https://stackoverflow.com/a/32726572/893113), which is declarative. Though I would probably write:
```
skip_if(conditions['condition one'], "test one", function () {
```

You could also write code which invokes [Mocha's `this.skip()`](https://stackoverflow.com/a/32820119/893113).

**Comment by Fishbowler** [comment]
I've killed off all of my arrow functions, added the `no-mocha-arrows` eslint rule, replaced my instances of `frisby.create('some text')` with `frisby.create(this.test.title)` and this solves the problem with `--fgrep`. There's still nothing working at all with `--grep` (e.g. looking to exclude any check containing "@flaky").

I can use `describe.skip(...)` and `it.skip(...)` to successfully disable tests in the repo. I like the idea of introducing an environment variable that can be used at runtime to determine whether to run a check, but I think I'd prefer to attempt this through a plugin and some globalSetup rather than make my entire codebase of checks "non-standard".

Unless anyone has any strong feelings about the outstanding bits here, I'm happy to leave the info here for future Googlers and close the issue.
