### ISSUE TITLE
Coveralls won't display information since Organisation change

### ISSUE THREAD

**Issue by Fishbowler** [IcedFrisby/IcedFrisby#96]
Since we moved the repo to an org, coveralls won't display detailed code coverage.
https://coveralls.io/builds/13811290/source?filename=lib%2Ficedfrisby.js

I've got some WIP on fixing up some quick wins on missing coverage, so gimme a nudge when this is fixed. V low priority, obvs.

**Comment by paulmelnikow** [comment]
I added this repo to both Coveralls and Travis and triggered a Travis build, so I _think_ it should show up in Coveralls in a few minutes.

**Comment by paulmelnikow** [comment]
Related: #98

**Comment by Fishbowler** [comment]
Sexy.
https://coveralls.io/builds/14568990/source?filename=lib%2Ficedfrisby.js
